# Site Settings
title:               xiaopf's zone
tagline:             "随便写东西的地方！"
description:
baseurl:            #"/Lagrange"
url:                #"https://xiaopf.github.io"
github:
  url:               #"https://xiaopf.github.io/Lagrange"
author:
  name:              "perfect_shaw"
  email:             "xiaopengfei123@gmail.com"
  twitter:           "perfect_shaw"
  instagram:         "perfect__shaw"
  github:            "xiaopf"
  # facebook:          "Le.Paul.94"
  linkedin:          "xiaopf"
navigation:
- title: About
  url: /about
- title: Writed
  url: /writed
- title: Contact
  url: /contact

# paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
